"""criar o atributo fone em usuario

Revision ID: 5e36f41d2b34
Revises: 69ed842d9ceb
Create Date: 2025-11-24 10:35:11.446774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e36f41d2b34'
down_revision: Union[str, Sequence[str], None] = '69ed842d9ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fone')
    # ### end Alembic commands ###
